name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      - name: Contributors with contributions count
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.contributors.contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_contributors: yes
          plugin_contributors_contributions: yes
      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
      - name: Sponsors goal
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.sponsors.svg
          token: ${{ secrets.METRICS_TOKEN_PERSONAL }}
          base: ""
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_past: yes
      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Europe/Berlin
      - name: Repositories and diff history
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.lines.history.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1
